Repository jphacks/A_2108, pull requests merged in 2021-10, with the labels that each got.

#186 UserIDで消すのを実装しました（くそコード）
  src/repository/user.go
Labels: enhancement

#187 デバッグモードを追加して，エラーメッセージをフロントに返すようにする。
  src/controller/controller.go
  src/controller/plan.go
  src/controller/user.go
  src/controller/yesman.go
  src/router/router.go
Labels: enhancement

#191 /placeのGETを修正
  src/place/api.go
Labels: fix

#190 [BUG] PlanがMockで帰ってきてるので, DBのデータを返すようにする
  src/controller/controller.go
Labels: enhancement

#192 動くんだよ
  src/controller/controller.go
  src/controller/plan.go
  src/controller/user.go
  src/controller/yesman.go
  src/place/api.go
  src/repository/user.go
  src/router/router.go
Labels: enhancement

#193 [FEATURE] UserのRepositoryに増えた機能のエンドポイントを生やす.
  src/controller/user.go
  src/controller/yesman.go
  src/router/router.go
Labels: enhancement

#196 fix
  src/repository/user.go
Labels: bug

#201 [BUG] int
  src/domain/plan.go
Labels: enhancement

#198 テスト環境を追加
  docker_compose/docker-compose.yml
  local-run.sh
  src/router/router_test_data.go
Labels: enhancement

#202 Feature/#188implement put method
  src/repository/plan.go
Labels: enhancement

#205 ますたあ
  docker_compose/docker-compose.yml
  local-run.sh
  src/controller/controller.go
  src/controller/user.go
  src/controller/yesman.go
  src/domain/plan.go
  src/repository/plan.go
  src/repository/repository.go
  src/repository/user.go
  src/router/router.go
  src/router/router_test_data.go
Labels: enhancement

#206 CreatorUserの追加処理実装
  src/repository/plan.go
Labels: bug

#207 まじまじ
  src/repository/plan.go
Labels: bug

#211 Add tracing code
  src/repository/user.go
Labels: documentation

#214 [FEATURE] post planのバグを消去
  src/controller/plan.go
Labels: bug

#215 パスワードはハッシュ化しましょう
  src/auth/password.go
  src/auth/password_test.go
  src/config/auth.go
  src/controller/register.go
Labels: enhancement

#217 バグの修正
  src/controller/plan.go
Labels: bug

#216 GetUserByIDがうまくいかない問題を修正
  src/repository/repository_test.go
  src/repository/user.go
Labels: bug

#218 fix bug
  src/controller/plan.go
Labels: bug

#223 直した
  src/repository/user.go
Labels: bug

#230 jwtのerror handlingを修正
  src/auth/jwt.go
Labels: enhancement

#231 /userを修正
  src/controller/user.go
  src/repository/repository_test.go
  src/router/router_test_data.go
Labels: fix

#232 いっくよー！
  README.md
  src/auth/jwt.go
  src/controller/user.go
  src/repository/repository_test.go
  src/router/router_test_data.go
Labels: enhancement

#236 Update README.md
  README.md
Labels: documentation

#235 Passwordのマスク処理を追加
  src/controller/user.go
Labels: bug, fix
